[pool]
downstream_listen_host = "127.0.0.1"
downstream_listen_port = 34254

[ln]
network = "regtest"
esplora_server_url = "https://blockstream.info/testnet/api"
gossip_source_rgs = "https://rapidsync.lightningdevkit.org/testnet/snapshot"

#[[ln.peers]]
##node_id = "fixme"
#address = "127.0.0.1:19846"
#
#[[ln.peers]]
##node_id = "fixme"
#address = "127.0.0.1:15352"